data:
  symbol: GER40.cash
  resample: 5min  # Gebruik 'min' i.p.v. 'T' voor pandas >= 2.2.0
  bars: 5000
strategies:
  rsi_reversion:
    enabled: true
    allocation: 100.0
    params:
      rsi_period: 14
      oversold: 30.0
      overbought: 70.0
      atr_period: 14
      sl_multiplier: 1.5
      tp_multiplier: 2.0
      use_next_open: true
engine:
  initial_capital: 10000
  risk_per_trade: 1.0
  max_positions: 3
  commission: 0.0002
  slippage: 0.0001
  time_exit_bars: 200
  allow_shorts: true
logging:
  level: DEBUG
  file: logs/trader.log