# Multi-Strategy Trading Configuration

# MT5 Connection (FTMO)
mt5:
  login: null  # Vul je FTMO account in
  password: null  # Vul je password in
  server: "FTMO-Demo"  # of "FTMO-Real"

# Data Settings
data:
  symbol: "GER40.cash"
  timeframe: "M1"  # Voor RSI is M1 of M5 beter!
  bars: 10000  # Meer data voor mean reversion
  resample: "5min"  # Resample naar 5 minuten

# Engine Settings
engine:
  initial_capital: 10000.0
  risk_per_trade: 1.0  # % of capital
  max_positions: 2  # Max 2 concurrent per strategy
  commission: 0.0002
  slippage: 0.0001
  time_exit_bars: 100  # Sneller exit voor mean reversion
  allow_shorts: true  # BELANGRIJK: Enable shorting!

# Strategy Settings
strategies:
  # RSI Mean Reversion - PRIMARY STRATEGY
  rsi_reversion:
    enabled: true
    allocation: 100.0  # 100% of capital (only active strategy)
    params:
      rsi_period: 14
      oversold: 30.0
      overbought: 70.0
      atr_period: 14
      sl_multiplier: 1.2  # Tighter stops voor mean reversion
      tp_multiplier: 1.8  # Smaller targets
      use_next_open: false  # Trade immediately on signal

# Logging
logging:
  level: "INFO"  # Change to DEBUG for more details
  file: "logs/trader.log"