trading:
  symbol: "GER40.cash"
  timeframe: "M1"
  initial_capital: 10000
  risk_per_trade: 1.0

strategy:
  sma_period: 200      # 200 min = ~3 uur
  atr_period: 60       # 60 min = 1 uur  
  sl_mult: 2.0         # Ruimere stop voor M1 noise
  tp_mult: 3.0         # Betere RR ratio
  volume_threshold: 1.0

backtest:
  commission: 0.0002
  time_exit_bars: 1440  # 1 dag in minuten