trading:
  symbol: "GER40.cash"
  timeframe: "M1"
  initial_capital: 10000
  risk_per_trade: 1.0

strategy:
  sma_period: 20
  atr_period: 14
  sl_multiplier: 1.5
  tp_multiplier: 2.5
  volume_threshold: 0.0   # <— TEMP uitzetten

backtest:
  commission: 0.0002
  time_exit_bars: 1440  # 1 dag in minuten