# config.yaml - Main Trading Configuration
# Supports both CSV and MT5 data sources

# Data settings
data:
  symbol: GER40.cash
  resample: 5min
  bars: 20000

# MT5 connection (optional - leave empty for demo/CSV mode)
mt5:
  symbol: GER40.cash
  timeframe: M1
  bars: 20000
  # Uncomment and fill for live MT5 connection:
  # login: 123456
  # password: "your_password"
  # server: "FTMO-Demo"

# Engine settings
engine:
  initial_capital: 10000.0
  risk_per_trade: 0.5
  max_positions: 3
  commission: 0.0002
  slippage: 0.0001
  time_exit_bars: 100
  allow_shorts: true
  min_risk_pts: 0.5

# Strategy settings - Choose ONE strategy
strategies:
  # RSI Mean Reversion Strategy
  rsi_reversion:
    enabled: true
    allocation: 100.0
    params:
      rsi_period: 14
      oversold: 35.0
      overbought: 65.0
      atr_period: 14
      sl_multiplier: 2.0
      tp_multiplier: 1.5

  # Simple Test Strategy (for framework validation)
  simple_test:
    enabled: false              # Set to true to use this instead
    allocation: 100.0
    params:
      entry_bar: 100
      trade_interval: 500
      max_trades: 10

# Trading hours and guards
guards:
  trading_hours_tz: "Europe/Berlin"
  trading_hours_start: "08:00"
  trading_hours_end: "22:00"
  min_atr_pts: 10.0
  cooldown_bars: 3
  max_trades_per_day: 10
  one_trade_per_timestamp: true